wallpaper {
    monitor = DP-4
    path = ~/.config/assets/wallpaper/outer-wilds.webp
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/assets/wallpaper/outer-wilds.webp
    fit_mode = cover
}
